version: 2

models:
  - name: stg_orders
    description: Cleaned orders from the Olist raw dataset
    columns:
      - name: order_id
        description: Unique identifier for each order
        data_tests:
          - unique
          - not_null

      - name: customer_id
        description: Foreign key to customers
        data_tests:
          - not_null

      - name: order_status
        description: Current status of the order
        data_tests:
          - not_null
          - accepted_values:
              values: ['delivered', 'shipped', 'canceled', 'unavailable', 
                       'invoiced', 'processing', 'created', 'approved']

  - name: stg_customers
    description: Cleaned customer data
    columns:
      - name: customer_id
        data_tests:
          - unique
          - not_null

  - name: stg_order_items
    description: Cleaned order items
    columns:
      - name: order_id
        data_tests:
          - not_null
      - name: price
        data_tests:
          - not_null

  - name: stg_sellers
    description: Cleaned seller data
    columns:
      - name: seller_id
        data_tests:
          - unique
          - not_null